name: Deploy (GitHub Pages)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload artifact (src/)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./src

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
